- label: 'Handbook'
  link: '/handbook'
  items:
    - label: 'Installation'
      link: '/installation'
      items:
        - label: 'WordPress Dashboard'
          link: '/wordpress-dashboard'
        - label: 'Manual installation'
          link: '/manual-installation'
    - label: 'Setup'
      link: '/setup'
      items:
        - label: 'Cryptographic secrets'
          link: '/cryptographic-secrets'
        - label: 'Security'
          link: '/security'
    - label: 'Plugin settings'
      link: '/plugin-settings'
      items:
        - label: 'General'
          link: '/general'
        - label: 'Order status'
          link: '/order-status'
        - label: 'REST API keys'
          link: '/rest-api-keys'
        - label: 'Tools'
          link: '/tools'
    - label: 'License keys'
      link: '/license-keys'
      items:
        - label: 'Overview'
          link: '/overview'
        - label: 'Adding license keys'
          link: '/adding-license-keys'
        - label: 'Editing license keys'
          link: '/editing-license-keys'
        - label: 'Exporting license keys'
          link: '/exporting-license-keys'
    - label: 'Generators'
      link: '/generators'
      items:
        - label: 'Overview'
          link: '/overview'
        - label: 'Adding generators'
          link: '/adding-generators'
        - label: 'Editing generators'
          link: '/editing-generators'
        - label: 'Generating license keys'
          link: '/generating-license-keys'
    - label: 'WooCommerce products'
      link: '/woocommerce-products'
      items:
        - label: 'Simple product'
          link: '/simple-product'
        - label: 'Variable product'
          link: '/variable-product'
        #- label: 'Simple Subscription'
        #  link: '/simple-subscription'
        #- label: 'Variable Subscription'
        #  link: '/variable-subscription'
    - label: 'WooCommerce orders'
      link: '/woocommerce-orders'
      items:
        - label: 'Order license keys'
          link: '/order-license-keys'
        - label: 'Resend license keys'
          link: '/resend-license-keys'
- label: 'Tutorials & How-To'
  link: '/tutorials-how-to'
  items:
    - label: 'REST API'
      link: '/rest-api'
      items:
        - label: 'Validating custom request data'
          link: '/validating-custom-request-data'
        - label: 'Modifying response data'
          link: '/modifying-response-data'
    - label: 'Theming'
      link: '/theming'
      items:
        - label: 'Template structure & Overriding templates via a theme'
          link: '/template-structure'
- label: 'REST API'
  link: '/rest-api'
  items:
    - label: 'Getting started'
      link: '/getting-started'
      items:
        - label: 'Requirements'
          link: '/requirements'
        - label: 'API keys'
          link: '/api-keys'
        - label: 'Test if the API is working'
          link: '/test-if-the-api-is-working'
    - label: 'Developer documentation'
      link: '/developer-documentation'
      items:
        - label: 'List licenses'
          link: '/list-licenses'
        - label: 'Retrieve a license'
          link: '/retrieve-license'
        - label: 'Create a license'
          link: '/create-license'
        - label: 'Update a license'
          link: '/update-license'
        - label: 'Activate a license'
          link: '/activate-license'
        - label: 'Deactivate a license'
          link: '/deactivate-license'
        - label: 'Validate a license'
          link: '/validate-license'
        - label: 'List generators'
          link: '/list-generators'
        - label: 'Retrieve a generator'
          link: '/retrieve-generator'
        - label: 'Create a generator'
          link: '/create-generator'
        - label: 'Update a generator'
          link: '/update-generator'
        #- label: 'Use a generator'
        #  link: '/use-generator'
        #- label: 'Update a product'
        #  link: '/update-product'
        #- label: 'Download the latest product'
        #  link: '/download-latest-product'

    - label: 'Libraries'
      link: '/libraries'
      items:
        - label: 'node.js'
          link: '/nodejs'
        - label: 'Python'
          link: '/python'
        - label: 'PHP'
          link: '/php'
        - label: 'Ruby'
          link: '/ruby'
        - label: 'C'
          link: '/c'
        - label: 'C#'
          link: '/c-sharp'
        - label: 'C++'
          link: '/cpp'
        - label: 'Golang'
          link: '/golang'
- label: 'Internal API'
  link: '/internal-api'
  items:
    - label: 'Database structure'
      link: '/database-structure'
      items:
        - label: 'lmfwc_api_keys'
          link: '/lmfwc-api-keys'
        - label: 'lmfwc_generators'
          link: '/lmfwc-generators'
        - label: 'lmfwc_licenses'
          link: '/lmfwc-licenses'
        - label: 'lmfwc_licenses_meta'
          link: '/lmfwc-licenses-meta'
    - label: 'Filters reference'
      link: '/filters-reference'
      items:
        - label: 'lmfwc_table_licenses_column_name'
          link: '/lmfwc-table-licenses-column-name'
        - label: 'lmfwc_table_licenses_column_value'
          link: '/lmfwc-table-licenses-column-value'
    - label: 'Actions reference'
      link: '/actions-reference'
      items:
        - label: 'lmfwc_event_post_order_license_keys'
          link: '/lmfwc-event-post-order-license-keys'
        #- label: 'lmfwc_simple_product_data_panel'
        #  link: '/lmfwc-simple-product-data-panel'
        #- label: 'lmfwc_simple_product_save'
        #  link: '/lmfwc-simple-product-save'
        #- label: 'lmfwc_variable_product_data_panel'
        #  link: '/lmfwc-variable-product-data-panel'
        #- label: 'lmfwc_variable_product_save'
        #  link: '/lmfwc-variable-product-save'
    - label: 'Functions reference'
      link: '/functions-reference'
      items:
        - label: 'lmfwc_add_license()'
          link: '/lmfwc-add-license'
        - label: 'lmfwc_get_license()'
          link: '/lmfwc-get-license'
        - label: 'lmfwc_get_licenses()'
          link: '/lmfwc-get-licenses'
        - label: 'lmfwc_update_license()'
          link: '/lmfwc-update-license'
        - label: 'lmfwc_delete_license()'
          link: '/lmfwc-delete-license'
        - label: 'lmfwc_activate_license()'
          link: '/lmfwc-activate-license'
        - label: 'lmfwc_deactivate_license()'
          link: '/lmfwc-deactivate-license'
        - label: 'lmfwc_add_license_meta()'
          link: '/lmfwc-add-license-meta'
        - label: 'lmfwc_get_license_meta()'
          link: '/lmfwc-get-license-meta'
        - label: 'lmfwc_update_license_meta()'
          link: '/lmfwc-update-license-meta'
        - label: 'lmfwc_delete_license_meta()'
          link: '/lmfwc-delete-license-meta'
